language: go

sudo: required

services:
  - docker

go:
  - "1.10"

env:
  - KUBERNETES_VERSION=1.9
  - KUBERNETES_VERSION=1.10
  - KUBERNETES_VERSION=1.11
  - KUBERNETES_VERSION=1.12
  - KUBERNETES_VERSION=1.13
  - KUBERNETES_VERSION=1.14

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce wget openssl
  - curl https://glide.sh/get | sh
  - glide install -v

script:
  - make ci-e2e-test KUBERNETES_VERSION=${KUBERNETES_VERSION}
